version: 0.2
phases:
  pre_build:
    commands:
      - echo $AWS_DEFAULT_REGION
      - echo $URL
  build: 
    steps:      
      - uses: actions/setup-node@v3        
        with:
          node-version: '18'
      - name: Install dependencies        
        run: |
          ls -la
          node index.js